[project]
name = "wg-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "pillow>=11.3.0",
    "pyyaml>=6.0.2",
    "qrcode>=8.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
